'''
Created on Dec 29, 2015

@author: ns
'''

from LastNameObjs import Nationality

basic = [['Afghan','Afghanistan'],
['Albanian','Albania'],
['Algerian','Algeria'],
['American','America','United States','New York'],
['Andorran','Andorra'],
['Angolan','Angola'],
['Argentinian','Argentina'],
['Armenian','Armenia'],
['Australian','Australia'],
['Austrian','Austria'],
['Azerbaijani','Azerbaijan'],
['Bahamian','Bahamas'],
['Bahraini','Bahrain'],
['Bangladeshi','Bangladesh'],
['Barbadian','Barbados'],
['Belarusian','Belarus','Belarusan'],
['Belgian','Belgium'],
['Belizean','Belize'],
['Beninese','Benin'],
['Bhutanese','Bhutan'],
['Bolivian','Bolivia'],
['Bosnian','Bosnia-Herzegovina'],
['Botswanan','Botswana'],
['Brazilian','Brazil'],
['Bruneian','Brunei'],
['Bulgarian','Bulgaria'],
['Burkinese','Burkina'],
['Burmese','Burma','Myanmar'],
['Burundian','Burundi'],
['Cambodian','Cambodia'],
['Cameroonian','Cameroon'],
['Canadian','Canada'],
['Cape Verdean','Cape Verde Islands'],
['Chadian','Chad'],
['Chilean','Chile'],
['Chinese','China'],
['Colombian','Colombia'],
['Congolese','Congo'],
['Costa Rican','Costa Rica'],
['Croatian','Croatia','Croat'],
['Cuban','Cuba'],
['Cypriot','Cyprus'],
['Czech','Czech Republic'],
['Danish','Denmark'],
['Djiboutian','Djibouti'],
['Dominican','Dominica'],
['Dominican','Dominican Republic'],
['Ecuadorean','Ecuador'],
['Egyptian','Egypt'],
['English','England','British','Britain'],
['Salvadorean','El Salvador'],
['Eritrean','Eritrea'],
['Estonian','Estonia'],
['Ethiopian','Ethiopia'],
['Fijian','Fiji'],
['Finnish','Finland'],
['French','France'],
['Gabonese','Gabon'],
['Gambian','Gambia, the'],
['Georgian','Georgia'],
['German','Germany'],
['Ghanaian','Ghana'],
['Greek','Greece'],
['Grenadian','Grenada'],
['Guatemalan','Guatemala'],
['Guinean','Guinea'],
['Guyanese','Guyana'],
['Haitian','Haiti'],
['Dutch','Holland','Netherlands'],
['Honduran','Honduras'],
['Hungarian','Hungary'],
['Icelandic','Iceland'],
['Indian','India'],
['Indonesian','Indonesia'],
['Iranian','Iran'],
['Iraqi','Iraq'],
['Irish','Ireland'],
['Israeli','Israel'],
['Italian','Italy'],
['Jamaican','Jamaica'],
['Japanese','Japan'],
['Jordanian','Jordan'],
['Kazakh','Kazakhstan'],
['Kenyan','Kenya'],
['Kuwaiti','Kuwait'],
['Laotian','Laos'],
['Latvian','Latvia'],
['Lebanese','Lebanon'],
['Liberian','Liberia'],
['Libyan','Libya'],
['Lithuanian','Lithuania'],
['Luxembourgish','Luxembourg'],
['Macedonian','Macedonia'],
['Madagascan','Madagascar'],
['Malawian','Malawi'],
['Malaysian','Malaysia'],
['Maldivian','Maldives'],
['Malian','Mali'],
['Maltese','Malta'],
['Mauritanian','Mauritania'],
['Mauritian','Mauritius'],
['Mexican','Mexico'],
['Moldovan','Moldova'],
['Monacan','Monaco'],
['Mongolian','Mongolia'],
['Montenegrin','Montenegro'],
['Moroccan','Morocco'],
['Mozambican','Mozambique'],
['Namibian','Namibia'],
['Nepalese','Nepal'],
['New Zealander','New Zealand'],
['Nicaraguan','Nicaragua'],
['Nigerien','Niger'],
['Nigerian','Nigeria'],
['North Korean','North Korea'],
['Norwegian','Norway'],
['Omani','Oman'],
['Pakistani','Pakistan'],
['Panamanian','Panama'],
['Papua New Guinean','Papua New Guinea'],
['Paraguayan','Paraguay'],
['Peruvian','Peru'],
['Philippine','Philippines'],
['Polish','Poland'],
['Portuguese','Portugal'],
['Qatari','Qatar'],
['Romanian','Romania'],
['Russian','Russia'],
['Rwandan','Rwanda'],
['Saudi','Saudi Arabia'],
['Scottish','Scotland'],
['Senegalese','Senegal'],
['Serbian','Serbia','Serb'],
['Seychellois','Seychelles'],
['Sierra Leonian','Sierra Leone'],
['Singaporean','Singapore'],
['Slovak','Slovakia'],
['Slovenian','Slovenia'],
['Somali','Somalia'],
['South African','South Africa'],
['South Korean','South Korea'],
['Spanish','Spain'],
['Sri Lankan','Sri Lanka'],
['Sudanese','Sudan'],
['Surinamese','Suriname'],
['Swazi','Swaziland'],
['Swedish','Sweden'],
['Swiss','Switzerland'],
['Syrian','Syria'],
['Taiwanese','Taiwan'],
['Tajik','Tajikistan'],
['Tanzanian','Tanzania'],
['Thai','Thailand'],
['Togolese','Togo'],
['Trinidadian','Trinidad and Tobago'],
['Tunisian','Tunisia'],
['Turkish','Turkey'],
['Turkmen','Turkmenistan'],
['Tuvaluan','Tuvalu'],
['Ugandan','Uganda'],
['Ukrainian','Ukraine'],
['Emirati','United Arab Emirates'],
['Uruguayan','Uruguay'],
['Uzbek','Uzbekistan'],
['Vanuatuan','Vanuatu'],
['Venezuelan','Venezuela'],
['Vietnamese','Vietnam'],
['Welsh','Wales'],
['Western Samoan','Western Samoa']]


nationalitylist = []
for i in basic:
    n = Nationality(i[0],i)
    nationalitylist.append(n)
